name: PHP Linting (Pint)

on: [ push, pull_request, workflow_dispatch ]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
          coverage: none

      - name: Composer Install
        run: composer install --no-interaction

      - name: Run Laravel Pint
        run: composer format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: PHP Linting (Pint) - Fix styling
          skip_fetch: true
